### ISSUE TITLE
Notes by quantization are looking a bit weird.

### ISSUE THREAD

**Issue by Brad2024** [TheRealJake12/Kade-Engine-Community#15]
The colors are correct, however the arrow direction does not change.
![image](https://user-images.githubusercontent.com/91802378/186285575-22640be9-587f-4e59-8758-14995c7f36ad.png)

**Comment by TheRealJake12** [comment]
you have rotate sprites enabled. Turn them off.

**Comment by TheRealJake12** [comment]
(I play with color quant on so I should know)

**Comment by Brad2024** [comment]
Thanks. By the way the note splashes are not the same color as the actual notes.

**Comment by TheRealJake12** [comment]
👍🏻 I'll steal bolos code for it

**Comment by BoloVEVO** [comment]
> 👍🏻 I'll steal bolos code for it

It seems you want to die.
