### ISSUE TITLE
Bug Report: Camera zoom not going back

### ISSUE THREAD

**Issue by BlazeTBV** [TheRealJake12/Kade-Engine-Community#17]
When the camera zoom to the beat is on, it doesnt go back to its previous position. making it infinitely zoom in.

**Comment by TheRealJake12** [comment]
known bug. Ill fix in a few hours or less

**Comment by BlazeTBV** [comment]
ok because i actually want to play around with this engine and maybe make amod with it

**Comment by TheRealJake12** [comment]
play the actions build once its done
