### ISSUE TITLE
Compiling help

### ISSUE THREAD

**Issue by thegamenig** [TheRealJake12/Kade-Engine-Community#27]
![image](https://github.com/TheRealJake12/Kade-Engine-Community/assets/142361218/33ec3a28-b5d0-4a02-a276-c511db3ed250)

**Comment by TheRealJake12** [comment]
did you run the easysetup.bat ?
it has a thing where it installs the msvc stuff for you

**Comment by thegamenig** [comment]
![image](https://github.com/TheRealJake12/Kade-Engine-Community/assets/142361218/06a11d4a-1cae-46f8-ad26-7601c067c940)

**Comment by TheRealJake12** [comment]
that didn't show anything. did you do the thing
![image](https://github.com/TheRealJake12/Kade-Engine-Community/assets/84357907/028a4d75-28c0-4d2d-96cd-62faf7a90037)

**Comment by CaptainDumb** [comment]
bro learned from that time in codename

**Comment by TheRealJake12** [comment]
true
