### ISSUE TITLE
Bug Report: easysetup doesnt install haxeui-core and haxeui-flixel

### ISSUE THREAD

**Issue by CaptainDumb** [TheRealJake12/Kade-Engine-Community#30]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.
no. fuck you :D
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 11 21H2 (10.22000.2538) x64 
## What version of the game are you using? Look in the bottom left corner of the main menu.
1.9.4-PRE1
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
run the batch file without anything installed and try to compile it (yes i used 4.3.4 for that)
## Please describe your issue. Provide extensive detail and images if possible.
read the title

**Comment by TheRealJake12** [comment]
I claim bullshit

**Comment by CaptainDumb** [comment]
commit 657 (1.9.4 PRE 1 release)

**Comment by TheRealJake12** [comment]
> commit 657 (1.9.4 PRE 1 release)

have you tried using latest commit?

**Comment by CaptainDumb** [comment]
yes, it doesnt install it too

**Comment by CaptainDumb** [comment]
fuck it im sticking to action builds
