### ISSUE TITLE
Bug Report: SongID doesnt support dashes, with exception of satin-panties

### ISSUE THREAD

**Issue by CaptainDumb** [TheRealJake12/Kade-Engine-Community#31]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Windows 11 21H2 Build 22000.2538
## What version of the game are you using? Look in the bottom left corner of the main menu.
newest action build
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
step 1: make a song with dash in its name
step 2: open it with chart editor thingy
step 3: press 7
step 4: crash
## Please describe your issue. Provide extensive detail and images if possible.
[yutube vid](https://youtu.be/Z1bIN8fVPxg)

**Comment by TheRealJake12** [comment]
did you reload the json? does your song have split vocals? test has split vocals so it'll think your song has split vocals too unless you set it to false.

**Comment by CaptainDumb** [comment]
freeplay has the same crash

**Comment by TheRealJake12** [comment]
> ### If you are playing a downloaded version of the game, what operating system are you using?
> 
> Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below. Windows 11 21H2 Build 22000.2538
> ## What version of the game are you using? Look in the bottom left corner of the main menu.
> 
> newest action build
> ## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
> 
> step 1: make a song with dash in its name step 2: open it with chart editor thingy step 3: press 7 step 4: crash
> ## Please describe your issue. Provide extensive detail and images if possible.
> 
> [yutube vid](https://youtu.be/Z1bIN8fVPxg)

watched the video, yeah. It's because your song probably doesn't have split vocals and in the chart, it's set to true. set it to false and see what happens.
