### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by TahirToprakKarabekiroglu** [TheRealJake12/Kade-Engine-Community#33]
Your note splash code is mostly based on my pull request at Psych repo, can you at least give me credit?

**Comment by TheRealJake12** [comment]
> you made a pr? I just glanced at 0.7.3's notesplash code with my own little twist on it.

you did infact make a pr, but I've never seen it before. I was cooking this stuff up before you made it lol

**Comment by CaptainDumb** [comment]
jokes on you, this code was stolen 15 times already

**Comment by TheRealJake12** [comment]
I'm gonna close this now
