### ISSUE TITLE
Bug Report:  compile error

### ISSUE THREAD

**Issue by Qwertcool54** [TheRealJake12/Kade-Engine-Community#37]
when i trying a compile this engine, i got this error

## What version of the game are you using? Look in the bottom left corner of the main menu.
idk, 1.9.4 or 1.9.3 (i didn't use release build)
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
no
## Please describe your issue. Provide extensive detail and images if possible.
source/kec/backend/chart/Song.hx:71: characters 12-13 : Unexpected .

**Comment by TheRealJake12** [comment]
what haxe version are you using? You gotta use atleast 4.3.4 I think.
I use 4.3.6 personally.

**Comment by Qwertcool54** [comment]
i use 4.2.5

**Comment by Qwertcool54** [comment]
ok, i install haxe 4.3.6, but i have now there error:
D:/lol/hscript-improved/git/hscript/macros/ClassExtendMacro.hx:30: characters 4-89 : Warning : switchTo is deprecated, use startOutro
source/kec/backend/Discord.hx:18: characters 60-66 : Class<hxdiscord_rpc.DiscordEventHandlers> has no field create
source/kec/backend/Discord.hx:46: characters 65-71 : Class<hxdiscord_rpc.DiscordRichPresence> has no field create
source/kec/backend/Discord.hx:22: characters 85-86 : Int should be Bool
source/kec/backend/Discord.hx:22: characters 85-86 : ... For function argument 'autoRegister'
source/kec/backend/modding/ModCore.hx:101: characters 26-75 : { modRoot : String, errorCallback : (error : polymod.PolymodError) -> Void } should be String
source/kec/backend/modding/ModCore.hx:101: characters 26-75 : ... For function argument 'modRoot'
source/kec/backend/modding/ModCore.hx:49: characters 11-23 : Class<polymod.Polymod> has no field loadOnlyMods
source/kec/backend/util/Paths.hx:351: characters 19-29 : Class<polymod.Polymod> has no field clearCache
source/kec/states/MainMenuState.hx:50: characters 12-24 : Class<polymod.Polymod> has no field loadOnlyMods

**Comment by Qwertcool54** [comment]
Okay, it's compiled now, thanks.

**Comment by TheRealJake12** [comment]
> Okay, it's compiled now, thanks.

no problem, glad I could help.
