### ISSUE TITLE
make a fxaa shader but real

### ISSUE THREAD

**Issue by Stilic** [TheRealJake12/Kade-Engine-Community#5]
yes there was a file in ke code lol
i think we can use [this one](https://www.shadertoy.com/view/ls3GWS).

**Comment by TheRealJake12** [comment]
will do. I pushed a early access 1.5.  Can you compile and see if it crashes on your end? specifically on MainMenuState.hx and FreeplayState.hx?

**Comment by Stilic** [comment]
> will do. I pushed a early access 1.5. Can you compile and see if it crashes on your end? specifically on MainMenuState.hx and FreeplayState.hx?

tommorow

**Comment by TheRealJake12** [comment]
thanks

**Comment by TheRealJake12** [comment]
it breaks the hud and shit

**Comment by Stilic** [comment]
> it breaks the hud and shit

wdym
i just suggested a idea and given a link
also it's your fault if you badly implemented the shader
i am fucking sure it could works if i do it myself (potentially for my own fnf engine)

**Comment by TheRealJake12** [comment]
bro... you wanna see how I do it?

**Comment by Stilic** [comment]
> bro... you wanna see how I do it?

i checked your code and uuuuuh
you should change the glsl code to make it compatible

**Comment by TheRealJake12** [comment]
alr

**Comment by Stilic** [comment]
maybe you can ask on psych engine discord
it has a shaders help channel

**Comment by TheRealJake12** [comment]
> maybe you can ask on psych engine discord
> it has a shaders help channel

Im not in it and I have 0 intensions on joining.

**Comment by TheRealJake12** [comment]
💀 how make it glsl work

**Comment by Stilic** [comment]
bro do you even know how to code?

**Comment by TheRealJake12** [comment]
> bro do you even know how to code?

bro... you fix it then lmao. I tried multiple things.
